apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nicksohl/user-management-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: backend-url
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: spring-jpa-hibernate-ddl-auto
        - name: JWT_ISSUER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: jwt-issuer
        - name: JWT_EXPIRATION_MILLIS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: jwt-expiration-millis
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
        - name: LETSENCRYPT_EMAIL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: letsencrypt-email
---
apiVersion: v1
kind: Service
type: ClusterIP
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000