apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  jwt-secret: d0lEQVFBQkFrQXpHbEZBUkZhdTdLMGI5RmNFd0lEQVFBQkFrQXpHbEZBUkZhdTdLMGI5RmNFd0lEQVFBQkFrQXpHbEZBUkZhdTdLMGI5RmNF
  letsencrypt-email: c3RlZmFuLmZ1cnJlckBlZHUudGVrby5jaAo=
