apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-mgmt.backend.name" . }}
  labels:
    {{- include "user-mgmt.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | quote }}
  letsencrypt-email: {{ .Values.backend.secrets.letsencryptEmail | quote }}
