apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-mgmt.frontend.name" . }}
  labels:
    {{- include "user-mgmt.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "user-mgmt.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
