apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "user-mgmt.postgres.name" . }}
  labels:
    {{- include "user-mgmt.postgres.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "user-mgmt.postgres.name" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "user-mgmt.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-mgmt.postgres.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-mgmt.postgres.name" . }}
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-mgmt.postgres.name" . }}
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db.name | quote }}
            - name: PGDATA
              value: {{ printf "/var/lib/postgresql/data/%s" .Values.postgres.storage.pgDataSubPath | quote }}
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-volume
      spec:
        accessModes:
          - {{ .Values.postgres.storage.accessMode }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
