apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-mgmt.postgres.name" . }}
  labels:
    {{- include "user-mgmt.postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.postgres.secrets.user | quote }}
  postgres-password: {{ .Values.postgres.secrets.password | quote }}
